# Generated by Django 3.2.7 on 2021-09-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecepientContacts',
            fields=[
                ('email_id', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('key_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email_id', models.EmailField(max_length=254)),
                ('authenticator', models.CharField(max_length=254)),
                ('recepients', models.ManyToManyField(to='mail_credentials.RecepientContacts')),
            ],
        ),
    ]
